### ISSUE TITLE
Incompatible with Entity Texture and Model Features.

### ISSUE THREAD

**Issue by SliMHaZe** [ThatJadenXgamer/Jadens-Nether-Expansion#56]
-- Head --
Thread: Render thread
Suspected Mod: 
	**Jaden's Nether Expansion (netherexp), Version: 2.0.2**
		Mixin class: net.jadenxgamer.netherexp.mixin.renderer.ThrownItemRendererMixin
		Target: net.minecraft.client.renderer.entity.ThrownItemRenderer
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.ThrownItemRenderer.handler$dbf000$netherexp$initTwo(ThrownItemRenderer.java:559)
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRenderers.m_257087_(EntityRenderers.java:164) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.entity.EntityRenderers.m_174049_(EntityRenderers.java:160) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_6213_(EntityRenderDispatcher.java:360) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:firstPerson.EntityRenderDispatcherMixin,pl:mixin:APP:mixins.essential.json:client.renderer.entity.Mixin_DontRenderHitboxOnEmulatedPlayer,pl:mixin:APP:immersive_aircraft.mixins.json:client.EntityRenderDispatcherMixin,pl:mixin:APP:entity_model_features-common.mixins.json:accessor.EntityRenderDispatcherAccessor,pl:mixin:APP:entity_model_features-common.mixins.json:rendering.MixinEntityRenderDispatcher,pl:mixin:APP:entity_texture_features-common.mixins.json:entity.misc.MixinEntityRenderDispatcher,pl:mixin:APP:friendsandfoes-common.mixins.json:EntityRenderDispatcherMixin,pl:mixin:APP:xenon.mixins.json:features.render.entity.shadows.EntityRenderDispatcherMixin,pl:mixin:APP:xenon.mixins.json:extras.entitydistance.EntityDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:SimpleReloadInstanceMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:client.Mixin_ThreadTaskExecutor,pl:mixin:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23548!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.essential.json:client.Mixin_ThreadTaskExecutor,pl:mixin:A}

**Comment by SliMHaZe** [comment]
This is my first time doing a github anything so sorry if this is confusing, pretty much, the new fireball textures are causing conflicts with ETF and EMF.

**Comment by ThatJadenXgamer** [comment]
could you send me the entire log file and crash report?
it's easier to read that way

**Comment by GustaMatos0** [comment]
Same thing here. Here comes my full log, it's the same error. 
[latest.log](https://github.com/user-attachments/files/17468824/latest.log)
[crash-2024-10-21_22.54.30-client.txt](https://github.com/user-attachments/files/17468833/crash-2024-10-21_22.54.30-client.txt)

**Comment by ThatJadenXgamer** [comment]
@GustaMatos0 Sinytra Connector is present in yours, please remove it and see if the game still crashes
if the game still crashes then send me the new latest log

**Comment by ThatJadenXgamer** [comment]
I made it so the redesigned fireballs no longer crash the game if they are null for whatever reason or if ETF/EMF are loaded
hopefully this should've fixed the issues

**Comment by SliMHaZe** [comment]
Wait so how do I get the updated version of the mod?

**Comment by ThatJadenXgamer** [comment]
It'll release sometime this week along with the halloween update
